export {default as Login} from "./Login/Login"
export {default as Otp} from "./Login/Otp"
export {default as LandingPage} from "./LandingPage/LandingPage"
export {default as Empty} from "./Empty/Empty"
export {default as Home} from "./Home/Home"