export default {
  carouselOne: require('../assets/images/carouselOne.jpeg'),
  carouselTwo: require('../assets/images/carouselTwo.jpeg'),
  carouselThree: require('../assets/images/carouselThree.jpeg'),
  homePage: require('../assets/images/homePage.jpeg'),
  hamburgerIcon: require('../assets/images/hamburgerIconTheme.png'),
  logRed: require('../assets/images/logRed.png'),
  logBlue: require('../assets/images/logBlue.png'),
  logYellow: require('../assets/images/logYellow.png'),
  logGreen: require('../assets/images/logGreen.png'),
  mailIcon: require('../assets/images/cross.png'),
  messageIcon: require('../assets/images/message.png'),
  heartIcon: require('../assets/images/heartIcon.png'),
  home: require('../assets/images/home.png'),
  search: require('../assets/images/searchTab.png'),
  location: require('../assets/images/location.png'),
  tickIcon: require('../assets/images/tick.png'),
  matriOne: require('../assets/images/matriOne.png'),
  matriTwo: require('../assets/images/matriTwo.png'),
  matriThree: require('../assets/images/matriThree.png'),
};