export default {
    LOGIN: "LOGIN",
    GET_DATA_FROM_API: "GET_DATA_FROM_API",
    LOAD_MORE_DATA: "LOAD_MORE_DATA",
    SWITCH_THEME: "SWITCH_THEME",
    LOGOUT: "LOGOUT",
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE"
}